version: '3.5'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: reservation_web_container
    environment:
      DEBUG: 'true'
      DB_HOST: db
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8100"
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8100:8100"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    container_name: reservation_postgres_container
    image: "postgres:13.4"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=reservation

volumes:
  postgres_data:
