version: '3.5'

services:
  web:
    build: .
    container_name: reservation_web_container
    command: python manage.py runserver 0.0.0.0:8010
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8010:8010"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    container_name: reservation_postgres_container
    image: postgres:14.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=reservation

volumes:
  postgres_data:
